<a href="https://colab.research.google.com/github/AzizOzmen/Clarusway_Data_Science_Materials/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import pandas as pd
import scipy as sp  # we imported related libraries for our study

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
help(np.random.normal)  # we looked at  inside the np.random.normal regarding what the parameters are

In [ ]:
samples = np.random.normal(loc=100, scale=15, size=1000)
samples  # we have generated  1,000 samples from the normal distribution 
         # using np.random.normal() with mean = 100 and standard deviation = 15 

array([109.84589479, 101.53846292,  92.53857213,  96.12082041,
       108.09684502, 113.72316759, 101.0495994 ,  89.93482377,
       105.28275973,  94.71707066, 109.36517611,  84.51263831,
        96.77066078, 104.71177726,  85.14772026, 112.77739183,
        96.15571091, 102.61059194,  99.30143663, 112.55647594,
        99.8361275 , 116.91611148, 101.0007493 ,  99.86800993,
       104.35172169,  82.72284903,  99.86230259, 135.42686965,
        80.83948787, 117.00616337,  96.85979197, 106.4408672 ,
       127.18487971,  94.75272568, 106.3155674 ,  89.55723511,
       132.91921104,  62.58983602,  92.22729852, 113.63300531,
       118.91713349,  99.97926061, 111.66496329,  70.94854366,
        94.23557521, 135.37946481,  74.49987165,  89.85611487,
       115.72817394,  81.95902549,  82.04413332, 113.7319109 ,
       111.08464499,  82.97590192,  99.92124527, 113.56863932,
       100.00520202,  98.33355375,  90.65862479, 112.47716319,
       101.65056246,  84.13561782,  97.11433161, 100.21

Compute the **mean**, **median**, and **mode**

In [ ]:
import scipy.stats as stats

mean = np.mean(samples)  # we computed the mean value for our generated samples
median = np.median(samples)  # we computed the median value for our generated samples
mode = stats.mode(samples)  # we computed the mode value for our generated samples
                            # WHATCH OUT: we used stats from scipy library for mode calcualtion

In [ ]:
samples.mean()

99.73342025064575

In [ ]:
mean

99.73342025064575

In [ ]:
median

99.92864460578403

In [ ]:
mode

ModeResult(mode=array([53.1733366]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)  # we computed minimum value for our generated samples 
max = np.max(samples)  # we computed maximum value for our generated samples
q1 = np.percentile(samples, 25)  # we computed the 25th percentile which represent 
                                 # the first quartile for our generated samples
q3 = np.percentile(samples, 75)  # we computed the 75th percentile which represent 
                                 # the third quartile for our generated samples
iqr = q3 - q1  # we computed the interquartile range for our generated samples

In [ ]:
samples.min()

53.173336596912094

In [ ]:
min

53.173336596912094

In [ ]:
samples.max()

143.23577521893174

In [ ]:
max

143.23577521893174

In [ ]:
q1

89.54505583599538

In [ ]:
q3

110.01431373725511

In [ ]:
iqr

20.469257901259724

In [ ]:
from scipy import stats
stats.iqr(samples)

20.469257901259724

In [ ]:
from scipy.stats import iqr 
iqr(samples)

20.469257901259724

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)  # we computed variance value for our generated samples
std_dev = np.std(samples)  # we computed standard deviation value for our generated samples

In [ ]:
samples.var()

218.36125593661419

In [ ]:
variance

218.36125593661419

In [ ]:
samples.std()

14.777051665897842

In [ ]:
std_dev

14.777051665897842

Compute the **skewness** and **kurtosis**

In [ ]:
"""
Skewness is a measure of symmetry, or more precisely, the lack of symmetry. 
A distribution, or data set, is symmetric if it looks the same to the left and 
right of the center point.  If the result of the computation is greater than zero, 
the distribution is positively skewed. If it's less than zero, it's negatively 
skewed and equal to zero means it's symmetric.

The skewness for a normal distribution is zero, and any symmetric data should 
have a skewness near zero. Negative values for the skewness indicate data that 
are skewed left and positive values for the skewness indicate data that are 
skewed right. By skewed left, we mean that the left tail is long relative to the
right tail. Similarly, skewed right means that the right tail is long relative to
the left tail. If the data are multi-modal, then this may affect the sign of the skewness.

Kurtosis is a measure of whether the data are heavy-tailed or light-tailed 
relative to a normal distribution. That is, data sets with high kurtosis tend to
have heavy tails, or outliers. Data sets with low kurtosis tend to have 
light tails, or lack of outliers.

When kurtosis is equal to 0, the distribution is mesokurtic. This means the kurtosis 
is the same as the normal distribution, it is mesokurtic (medium peak). The kurtosis 
of a mesokurtic distribution is neither high nor low, rather it is considered to 
be a baseline for the two other classifications.

Positive values of kurtosis indicate that a distribution is peaked and possess 
thick tails. Leptokurtic distributions have positive kurtosis values. A leptokurtic 
distribution has a higher peak and taller (i.e. fatter and heavy) tails than a normal distribution.

Negative values of kurtosis indicate that a distribution is flat and has thin tails. 
Platykurtic distributions have negative kurtosis values. A platykurtic distribution 
is flatter (less peaked) when compared with the normal distribution, with fewer 
values in its shorter (i.e. lighter and thinner) tails.

""" 

In [ ]:
skewness = stats.skew(samples)  # we computed skewness value for our generated samples
kurtosis = stats.kurtosis(samples)  # we computed kurtosis value for our generated samples

In [ ]:
skewness

-0.042466663222598816

In [ ]:
kurtosis  

-0.09640128573368845

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([1, 22, 33, 45, 55, 68, 77, 83, 94, 13], dtype=int)
y

array([ 1, 22, 33, 45, 55, 68, 77, 83, 94, 13])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x, y)
r

array([[1.        , 0.56459624],
       [0.56459624, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = x.corr(y, method='pearson')
r

0.7586402890911867

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = x.corr(y, method="spearman")
rho

0.9757575757575757

In [ ]:
rho = x.corr(y, method="kendall")
rho

0.911111111111111

In [ ]:
import numpy as np
from scipy.stats import spearmanr

In [ ]:
rho = stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
tips.shape

(244, 7)

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
a = tips['total_bill'].corr(tips['tip'], method='pearson')
a

0.6757341092113641

In [ ]:
b = tips['total_bill'].corr(tips['size'], method='pearson')
b

0.5983151309049022

In [ ]:
c = tips['tip'].corr(tips['size'], method='pearson')
c

0.4892987752303577